### ISSUE TITLE
English language support?

### ISSUE THREAD

**Issue by lammel-hub** [hamonikr/hamonikr-stacer#2]
자유롭게 자신의 의견을 적어주세요.

Hello,
It is admirable of you to pick up Stacer and keep it relevant going forward. 

I do not speak Korean, but believe HarmoniKR is an important OS. It is my understanding it is related to Linux Mint, which has one of the largest desktop user-bases outside the Republic of Korea. 

Is it possible for you to include a language option for English, making it accessible also for non-korean speaking users?

**Comment by chaeya** [comment]
@lammel-hub  Thank you for your interest in our project.
This project is a modified version of the upstream project tailored for HamoniKR OS.
You can find the information you are looking for in the upstream project, which is maintained in English.

Upstream: https://github.com/oguzhaninan/Stacer

**Comment by lammel-hub** [comment]
thank you for your rapid response! unfortunately, the upstream is no longer maintained, that is why I sent the question to you, in the hope that you will carry on the torch of Stacer.
